fix the ci pipeliene

name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - "feature/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      # Step 3: Set environment variables from GitHub Secrets
      - name: Set environment variables
        run: echo >> "set env vars"
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
          IMGUR_CLIENT_SECRET: ${{ secrets.IMGUR_CLIENT_SECRET }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      # Step 4: Build the application using Maven
      - name: Build with Maven
        run: mvn clean install --batch-mode

      # Step 5: Run tests
      - name: Run tests
        run: mvn test --batch-mode
